format = """
[ ](bg:#7400B8 fg:#000000)\
$username\
[](bg:#5E60CE fg:#7400B8)\
$directory\
[](fg:#5E60CE bg:#4EA8DE)\
$git_branch\
$git_status\
[](fg:#4EA8DE bg:#56CFE1)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#56CFE1 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#80FFD8)\
$time\
[ ](fg:#80FFD8)\
\n$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#7400B8"
style_root = "bg:#7400B8"
format = '[$user ]($style)'

[directory]
style = "bg:#5E60CE"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[elm]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[git_branch]
symbol = ""
style = "bg:#4EA8DE"
format = '[[ $symbol $branch ](bg:#4EA8DE)]($style)'

[git_status]
style = "bg:#4EA8DE"
format = '[[($all_status$ahead_behind )](bg:#4EA8DE)]($style)'

[golang]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[haskell]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[java]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[julia]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[nodejs]
symbol = ""
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[nim]
symbol = " "
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[rust]
symbol = ""
style = "bg:#56CFE1"
format = '[[ $symbol ($version) ](bg:#56CFE1)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#80FFD8"
format = '[[ ♥ $time ](bg:#80FFD8 fg:#5390d9)]($style)'

